# Site wide configuration

title:            carlhicks[dot]me
locale:           en_US
url:               http://localhost:4000  #http://carlhicks.me


# Jekyll configuration

permalink:   /blog/:categories/:year/:month/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Carl Hicks
  avatar: bio-photo.jpg
  bio: "Just another Guy[developer] with a blog."
  email: mail@carlhicks.me
  disqus-shortname: carlhicksdotme
  twitter: cahicks1
  facebook: carlhicksiii
  google:
    plus: #username
    analytics: UA-54179433-1 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: hicksca
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: carlahicks
  instagram: hicksca1
  lastfm: #username
  tumblr: hicksca
  pinterest: hicksca
  foursquare: cahicks1
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
